// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 33: // ['!','!']
			return 2
		case r == 34: // ['"','"']
			return 3
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 5
		case r == 40: // ['(','(']
			return 6
		case r == 41: // [')',')']
			return 7
		case r == 43: // ['+','+']
			return 8
		case r == 44: // [',',',']
			return 9
		case r == 47: // ['/','/']
			return 10
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 59: // [';',';']
			return 12
		case r == 61: // ['=','=']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case r == 91: // ['[','[']
			return 15
		case r == 93: // [']',']']
			return 16
		case r == 95: // ['_','_']
			return 14
		case 97 <= r && r <= 100: // ['a','d']
			return 14
		case r == 101: // ['e','e']
			return 17
		case r == 102: // ['f','f']
			return 18
		case 103 <= r && r <= 104: // ['g','h']
			return 14
		case r == 105: // ['i','i']
			return 19
		case 106 <= r && r <= 118: // ['j','v']
			return 14
		case r == 119: // ['w','w']
			return 20
		case 120 <= r && r <= 122: // ['x','z']
			return 14
		case r == 123: // ['{','{']
			return 21
		case r == 124: // ['|','|']
			return 22
		case r == 125: // ['}','}']
			return 23
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 24
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case 1 <= r && r <= 33: // [\u0001,'!']
			return 25
		case r == 34: // ['"','"']
			return 26
		case 35 <= r && r <= 91: // ['#','[']
			return 25
		case r == 92: // ['\','\']
			return 27
		case 93 <= r && r <= 127: // [']',\u007f]
			return 25
		case 128 <= r && r <= 65532: // [\u0080,\ufffc]
			return 28
		case 65534 <= r && r <= 1114111: // [\ufffe,\U0010ffff]
			return 28
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case r == 38: // ['&','&']
			return 29
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 30
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 31
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 33
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 107: // ['a','k']
			return 33
		case r == 108: // ['l','l']
			return 34
		case 109 <= r && r <= 122: // ['m','z']
			return 33
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 116: // ['a','t']
			return 33
		case r == 117: // ['u','u']
			return 35
		case 118 <= r && r <= 122: // ['v','z']
			return 33
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 101: // ['a','e']
			return 33
		case r == 102: // ['f','f']
			return 36
		case 103 <= r && r <= 122: // ['g','z']
			return 33
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 103: // ['a','g']
			return 33
		case r == 104: // ['h','h']
			return 37
		case 105 <= r && r <= 122: // ['i','z']
			return 33
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		case r == 124: // ['|','|']
			return 38
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case 1 <= r && r <= 33: // [\u0001,'!']
			return 25
		case r == 34: // ['"','"']
			return 26
		case 35 <= r && r <= 91: // ['#','[']
			return 25
		case r == 92: // ['\','\']
			return 27
		case 93 <= r && r <= 127: // [']',\u007f]
			return 25
		case 128 <= r && r <= 65532: // [\u0080,\ufffc]
			return 28
		case 65534 <= r && r <= 1114111: // [\ufffe,\U0010ffff]
			return 28
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case 1 <= r && r <= 33: // [\u0001,'!']
			return 39
		case r == 34: // ['"','"']
			return 40
		case 35 <= r && r <= 91: // ['#','[']
			return 39
		case r == 92: // ['\','\']
			return 40
		case 93 <= r && r <= 127: // [']',\u007f]
			return 39
		case 128 <= r && r <= 65532: // [\u0080,\ufffc]
			return 41
		case 65534 <= r && r <= 1114111: // [\ufffe,\U0010ffff]
			return 41
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case 1 <= r && r <= 33: // [\u0001,'!']
			return 25
		case r == 34: // ['"','"']
			return 26
		case 35 <= r && r <= 91: // ['#','[']
			return 25
		case r == 92: // ['\','\']
			return 27
		case 93 <= r && r <= 127: // [']',\u007f]
			return 25
		case 128 <= r && r <= 65532: // [\u0080,\ufffc]
			return 28
		case 65534 <= r && r <= 1114111: // [\ufffe,\U0010ffff]
			return 28
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 42
		default:
			return 30
		}
	},
	// S31
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 33
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 33
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 114: // ['a','r']
			return 33
		case r == 115: // ['s','s']
			return 43
		case 116 <= r && r <= 122: // ['t','z']
			return 33
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 109: // ['a','m']
			return 33
		case r == 110: // ['n','n']
			return 44
		case 111 <= r && r <= 122: // ['o','z']
			return 33
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 33
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 104: // ['a','h']
			return 33
		case r == 105: // ['i','i']
			return 45
		case 106 <= r && r <= 122: // ['j','z']
			return 33
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case 1 <= r && r <= 33: // [\u0001,'!']
			return 25
		case r == 34: // ['"','"']
			return 26
		case 35 <= r && r <= 91: // ['#','[']
			return 25
		case r == 92: // ['\','\']
			return 27
		case 93 <= r && r <= 127: // [']',\u007f]
			return 25
		case 128 <= r && r <= 65532: // [\u0080,\ufffc]
			return 28
		case 65534 <= r && r <= 1114111: // [\ufffe,\U0010ffff]
			return 28
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case 1 <= r && r <= 33: // [\u0001,'!']
			return 25
		case r == 34: // ['"','"']
			return 26
		case 35 <= r && r <= 91: // ['#','[']
			return 25
		case r == 92: // ['\','\']
			return 27
		case 93 <= r && r <= 127: // [']',\u007f]
			return 25
		case 128 <= r && r <= 65532: // [\u0080,\ufffc]
			return 28
		case 65534 <= r && r <= 1114111: // [\ufffe,\U0010ffff]
			return 28
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case 1 <= r && r <= 33: // [\u0001,'!']
			return 25
		case r == 34: // ['"','"']
			return 26
		case 35 <= r && r <= 91: // ['#','[']
			return 25
		case r == 92: // ['\','\']
			return 27
		case 93 <= r && r <= 127: // [']',\u007f]
			return 25
		case 128 <= r && r <= 65532: // [\u0080,\ufffc]
			return 28
		case 65534 <= r && r <= 1114111: // [\ufffe,\U0010ffff]
			return 28
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 42
		case r == 47: // ['/','/']
			return 46
		default:
			return 30
		}
	},
	// S43
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 100: // ['a','d']
			return 33
		case r == 101: // ['e','e']
			return 47
		case 102 <= r && r <= 122: // ['f','z']
			return 33
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 33
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 107: // ['a','k']
			return 33
		case r == 108: // ['l','l']
			return 48
		case 109 <= r && r <= 122: // ['m','z']
			return 33
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 33
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 100: // ['a','d']
			return 33
		case r == 101: // ['e','e']
			return 49
		case 102 <= r && r <= 122: // ['f','z']
			return 33
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 33
		case 97 <= r && r <= 122: // ['a','z']
			return 33
		}
		return NoState
	},
}
